name: CI

on:
  push:
    branches:
      - dev
      - master

  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set environment variable based on branch
        id: set_env
        run: |
          # Create variable name based on the branch
          VAR_NAME="ENV_${GITHUB_REF_NAME}"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Variable Name: $VAR_NAME"
          
          # Directly set ENV from the repository variable
          echo "ENV=${{ vars[format('{0}', VAR_NAME)] }}" >> $GITHUB_ENV

      - name: Print environment variable (debugging step)
        run: |
          echo "ENV variable is: $ENV"

      - name: Build and deploy app
        run: |
          echo "Jump App is being built for ${GITHUB_REF_NAME} environment"
          echo $ENV
          ./scripts/frontendDeployer.sh ${{ github.head_ref || github.ref_name }}

