name: CI

on:
  push:
    branches:
      - dev
      - master

  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment to deploy to"
        required: true
        options:
          - "dev"
          - "prod"
jobs:
 
  build-frontend:
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set environment variables
        run: |
          export VAR_NAME=$(printf "ENV_%s" $GITHUB_REF_NAME)
          echo "ENV=${!VAR_NAME}" >> $GITHUB_ENV
      - name: Print environment variable (debugging step)
        run: |
          echo "ENV variable is: $ENV"
        env:
          ENV: ${{ env.ENV }}

      - name: Build and deploy app
        run: |
          echo "Jump App is being built for development environment";
          ./scripts/frontendDeployer.sh ${{ github.head_ref || github.ref_name }}
