name: CI

on:
  push:
    branches:
      - dev
      - qa
      - uat
      - main

  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set environment variables
        run: |
          # Determine the environment variable based on the branch
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            ENV="${{ vars.ENV_DEV }}"
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            ENV="${{ vars.ENV_QA }}"
          elif [[ "${{ github.ref }}" == "refs/heads/uat" ]]; then
            ENV="${{ vars.ENV_UAT }}"
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            ENV="${{ vars.ENV_PROD }}"
          else
            echo "No matching environment found."
            exit 1
          fi

          echo "ENV=$ENV" >> $GITHUB_ENV  # Export the environment variable

      - name: Print environment variable (debugging step)
        run: |
          echo "ENV variable is: $ENV"
        env:
          ENV: ${{ env.ENV }}

      - name: Build and deploy app
        run: |
          echo "Jump App is being built for the environment: $ENV"
          ./scripts/frontendDeployer.sh ${{ github.head_ref || github.ref_name }}

