name: CI

on:
  push:
    branches:
      - dev
      - qa
      - uat
      - master

  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment to deploy to"
        required: true
        options:
          - "dev"
          - "qa"
          - "uat"
          - "prod"

jobs:
 
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]] || [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
            # Use the repository variable for dev
            ENV="${{ vars.ENV_DEV }}"
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]] || [[ "${{ github.event.inputs.environment }}" == "qa" ]]; then
            # Use the repository variable for qa
            ENV="${{ vars.ENV_QA }}"
          elif [[ "${{ github.ref }}" == "refs/heads/uat" ]] || [[ "${{ github.event.inputs.environment }}" == "uat" ]]; then
            # Use the repository variable for uat
            ENV="${{ vars.ENV_UAT }}"
          elif [[ "${{ github.ref }}" == "refs/heads/master" ]] || [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
            # Use the repository variable for production
            ENV="${{ vars.ENV_PROD }}"
          else
            echo "No matching environment found."
            exit 1
          fi
          echo "ENV=$ENV" >> $GITHUB_ENV  # Export the environment variable

      - name: Print environment variable (debugging step)
        run: |
          echo "ENV variable is: $ENV"
        env:
          ENV: ${{ env.ENV }}

      - name: Build and deploy app
        run: |
          echo "Jump App is being built for $ENV environment";
          ./scripts/frontendDeployer.sh ${{ github.head_ref || github.ref_name }}

