name: CI

on:
  push:
    branches:
      - dev
      - master

  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment to deploy to"
        required: true
        options:
          - "dev"
          - "prod"
          
jobs:
 
  build-frontend:
    runs-on: ubuntu-latest

    env:  # Define your environment variables here
      ENV_DEV: "Development Value"
      ENV_PROD: "Production Value"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Create Variables
        id: vars
        run: |
          branch=${GITHUB_REF_NAME}
          echo "::set-output name=ENV_VAR_NAME::ENV_${branch^^}" # Output ENV variable name

      - name: Set environment variables
        run: |
          # Fetch the environment variable dynamically using bash
          ENV_VAR_NAME="${{ steps.vars.outputs.ENV_VAR_NAME }}" # The variable name
          ENV_VALUE="${!ENV_VAR_NAME}"  # This expands the variable stored inside ENV_VAR_NAME
          echo "Resolved ENV_VALUE: $ENV_VALUE"
          echo "ENV_VALUE=$ENV_VALUE" >> $GITHUB_ENV  # Set the value to the GitHub environment

      - name: Build and deploy app
        run: |
          echo "Jump App is being built for $ENV_VALUE environment";
          ./scripts/frontendDeployer.sh ${{ github.head_ref || github.ref_name }}

